# train and val datasets (image directory or *.txt file with image paths)
train: /content/pytorch_custom_yolo_training-7/data/model-trains/train.txt
val: /content/pytorch_custom_yolo_training-7/data/model-trains/val.txt
test: /content/pytorch_custom_yolo_training-7/data/model-trains/test.txt

# number of classes
nc: 1

# class names
names: ['Train']